# Practice Report

This chapter describes a formative exercise for this class.

## Assessment information

-   You will be given a dataset and a finished report on that data. Your task is to write the code that produces the report.
-   Please check Moodle for the deadline.
-   The solution will be released immediately after the deadline on Moodle.
-   This is a formative activity and does not count towards your course grade.
-   You should submit two files to Moodle to complete the exercise - your .Rmd file and the knitted html document.
-   You should not expect to be able to complete it until you have worked through Chapters 1-5 (although particularly Chapters 1-3).
-   The practice report will not be individually graded. Instead, we will release the solution file so that you can compare your code to our solution as generic feedback. If you would like to discuss any aspect of the report, you can attend office hours.

## Intended Learning Outcomes (ILOs)

### Knowledge and skills {-}

-   Demonstrate the ability to use R for data wrangling and visualisation
-   Demonstrate the ability to use R Markdown for reproducible reports

### Evaluation {-}

-   Demonstrate the ability to evaluate an output to understand the underlying data wrangling and analysis

### Communication {-}

-   Demonstrate the ability to produce a clear and coherent report with appropriate spelling, grammar, and layout

## Details and files

-   There are two files you need to download. The first is the dataset: <a href="https://healthteachr.github.io/data/formative_data.csv" download>formative_data.csv</a>. The second is the finished report that you need to backwards engineer from the data: [formative_report_output.html](https://healthteachr.github.io/data/formative_report_output.html).

-   There are multiple ways to achieve the same outcome when coding. You do not have to use the same solutions that we did; what matters is that the output is the same.

-   All plots, and tables in the report should be fully reproducible.

-   For any visuals, you should get as close to the example report as possible, although we recognise that it may be difficult to know the exact theme or colours used without seeing the code.

-   In order to replicate the report you will need the following skills:

    -   Data visualisation
    -   Summarising data in tables

Almost everything you need to do generate this report will have been covered at least once in the workbook, but you should also expect to need to Google some things -- being able to search for alternative solutions is such a key skill for programming.

## Support

This assessment will require you to use the skills you have learned from Chapter 1 (Intro to R and R Studio) up to and including Chapter 5 (Data Summaries) of the Applied Data Skills workbook.

Google and Stack Overflow will help you a lot. Remember to include the names of packages and functions to help ensure the results are closer to what you're trying to do.

## Helpful hints

A few hints to help you on your way:

-   This dataset is bigger than the ones you've used before, which means you might find it takes R a little longer to complete certain tasks.
-   clean_names()
-   Googling "ggplot rotate x axis labels" will help you out.
-   table()

## Why am I being assessed like this?

Whilst most of the skills required for the practice report have been explicitly taught, there are minor bits of the coding that will require you to look up solutions independently. This will be good practice for applying your coding skills to your own work.
